export const candidatesData = [
    {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Disqualified",
        lock: true,
        details: 3,
    },
    {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Disqualified",
        lock: true,
        details: 3,
    },        {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Disqualified",
        lock: true,
        details: 3,
    },        {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Disqualified",
        lock: true,
        details: 3,
    },        {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Disqualified",
        lock: true,
        details: 3,
    },        {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Disqualified",
        lock: true,
        details: 3,
    },        {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Disqualified",
        lock: true,
        details: 3,
    },        {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Disqualified",
        lock: true,
        details: 3,
    },        {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        status: "Active",
        lock: true,
        details: 1,
    },
    {
        name: "Hanna Samuel",
        sect: 3,
        year: 5,
        dept: "Software Engineering",
        status: "Eliminated",
        lock: false,
        details: 2,
    }
]