export const UsersData = [
    {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        details: 1,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        details: 2,
    },
    {
        name: "Amanuel Teklu",
        sect: 1,
        year: 3,
        dept: "Chemical Engineering",
        details: 3,
    },
    {
        name: "Assegid Assefa",
        sect: 1,
        year: 2,
        dept: "Information Technology",
        details: 4,
    },
    {
        name: "Haftom Legese",
        sect: 2,
        year: 4,
        dept: "Civil Engineering",
        details: 5,
    },
    {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        details: 6,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        details: 7,
    },
    {
        name: "Amanuel Teklu",
        sect: 1,
        year: 3,
        dept: "Chemical Engineering",
        details: 8,
    },
    {
        name: "Assegid Assefa",
        sect: 1,
        year: 2,
        dept: "Information Technology",
        details: 9,
    },
    {
        name: "Haftom Legese",
        sect: 2,
        year: 4,
        dept: "Civil Engineering",
        details: 10,
    },
    {
        name: "Kaleb Mesfin",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        details: 1,
    },
    {
        name: "Daniel Terefe",
        sect: 2,
        year: 5,
        dept: "Software Engineering",
        details: 2,
    },
    {
        name: "Amanuel Teklu",
        sect: 1,
        year: 3,
        dept: "Chemical Engineering",
        details: 3,
    },
    {
        name: "Assegid Assefa",
        sect: 1,
        year: 2,
        dept: "Information Technology",
        details: 4,
    },
    {
        name: "Haftom Legese",
        sect: 2,
        year: 4,
        dept: "Civil Engineering",
        details: 5,
    },
]